package opticnav.ardd.protocol.consts;
/*
 * This file was generated by genconst.py. DO NOT MODIFY!
 */
public final class ARDdAdminProtocol {
    public static final int MAX_MAP_IMAGE_SIZE=16777216;
    public static final class Commands {
        public static final int REGARD=0;
        public static final int ARDINFO=1;
        public static final int DEPLOY_INSTANCE=2;
    }
}