package opticnav.ardd.protocol.consts;
/*
 * This file was generated by genconst.py. DO NOT MODIFY!
 */
public final class ARDdARDProtocol {
    public static final int NO_ARD=0;
    public static final class Channels {
        public static final int GATEKEEPER=0;
        public static final int CONNECTED=1;
    }
    public static final class ReqCodes {
        public static final int REGISTERED=0;
        public static final int COULDNOTREGISTER=1;
        public static final int CANCELLED=2;
    }
    public static final class Commands {
        public static final int REQCODES=0;
        public static final int CONNECT=1;
    }
    public static final class Connected {
        public static final class Commands {
            public static final int LIST_INSTANCES=0;
        }
    }
}
