package opticnav.daemon.protocol.consts;
/*
 * This file was generated by genconst.py. DO NOT MODIFY!
 */
public final class ARDdARDProtocol {
	public static final int NO_ARD=0;
	public static final class Channels {
		public static final int GATEKEEPER=0;
		public static final int CONNECTED=1;
	}
	public static final class ReqCodes {
		public static final int REGISTERED=0;
		public static final int COULDNOTREGISTER=1;
		public static final int CANCELLED=2;
	}
	public static final class Commands {
		public static final int REQCODES=0;
		public static final int CONNECT=1;
	}
	public static final class Connected {
		public static final class Instance {
			public static final class SubscriberCommands {
				public static final int CREATE_MARKER=0;
				public static final int MOVE_MARKER=1;
				public static final int REMOVE_MARKER=2;
			}
			public static final class Commands {
				public static final int MOVE=0;
			}
		}
		public static final class Commands {
			public static final int LIST_INSTANCES=0;
			public static final int JOIN_INSTANCE=1;
		}
	}
}
