divert(-1)
This file was generated by genconst.py. DO NOT MODIFY!
divert(0)dnl
define(Web__MaxLength__USERNAME,25)dnl
define(Web__MaxLength__PASSWORD,25)dnl
define(Web__MaxLength__RESOURCE_TYPE,127)dnl
define(Web__MaxLength__MAP_NAME,64)dnl
define(Web__MaxLength__MARKER_NAME,64)dnl
