package opticnav.persistence.web.consts;
/*
 * This file was generated by genconst.py. DO NOT MODIFY!
 */
public final class WebPersistenceConsts {
	public static final class MaxLength {
		public static final int USERNAME=25;
		public static final int PASSWORD=25;
		public static final int RESOURCE_TYPE=127;
		public static final int MAP_NAME=64;
		public static final int MARKER_NAME=64;
	}
}
